name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ "main" ]  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}       # Set this secret to your Droplet's IP or hostname
          username: invoicing                 # The SSH user on your Droplet
          key: ${{ secrets.SSH_KEY }}         # The private key (without a passphrase) stored as a secret
          script: |
            # Navigate to your project directory; adjust this path if needed
            cd /var/www/html/invoicing

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Installing Composer dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "Running Phinx migrations..."
            php vendor/bin/phinx migrate -e production

            echo "Deployment finished successfully!"
