name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ "main" ]  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Debug Environment
        run: |
          echo "GOOGLE_REDIRECT_URI is: $GOOGLE_REDIRECT_URI"
          env | grep GOOGLE

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}       # Set this secret to your Droplet's IP or hostname
          username: invoicing                 # The SSH user on your Droplet
          key: ${{ secrets.SSH_KEY }}         # The private key (without a passphrase) stored as a secret
          script: |
            echo "Exporting environment variables..."
            export GOOGLE_REDIRECT_URI="${GOOGLE_REDIRECT_URI}"
            echo "GOOGLE_REDIRECT_URI is: $GOOGLE_REDIRECT_URI"
            echo ${{ secrets.GOOGLE_REDIRECT_URI }}
            echo secrets.SSH_HOST
            echo $secrets.SSH_HOST
            echo ${{ secrets.GOOGLE_REDIRECT_URI }}
            # Navigate to your project directory; adjust this path if needed
            cd /var/www/html/invoicing

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Installing Composer dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "Running Phinx migrations..."
            php vendor/bin/phinx migrate -e production

            echo "Deployment finished successfully!"
