name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ "main" ]  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}       # Droplet's IP or hostname
          username: invoicing                 # SSH user on your Droplet
          key: ${{ secrets.SSH_KEY }}         # Private key stored as a secret
          script: |
            echo "Creating .env file..."
            cat > /var/www/html/invoicing/.env <<'EOF'
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
            EOF
            echo ".env file created."
            
            # Navigate to project root
            cd /var/www/html/invoicing

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Installing Composer dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "Running Phinx migrations..."
            php vendor/bin/phinx migrate -e production

            echo "Building frontend..."
            cd frontend
            npm ci
            npm run build
            cd ..

            echo "Deploying frontend build..."
            # Copy the frontend build (Vite output) into the public folder.
            rsync -av --delete frontend/dist/ public/

            # Check if Apache reverse proxy config is already deployed;
            # if not, copy it from deploy/apache.conf and enable the site.
            if [ ! -f /etc/apache2/sites-available/invoicing.conf ]; then
              echo "Deploying reverse proxy configuration..."
              sudo cp deploy/apache.conf /etc/apache2/sites-available/invoicing.conf
              sudo a2ensite invoicing.conf
            else
              echo "Reverse proxy configuration already exists."
            fi

            echo "Reloading Apache..."
            sudo systemctl reload apache2

            echo "Deployment finished successfully!"
